# Settings For github-pages

email: your-email@example.com
baseurl: "computers" # the subpath of your site, e.g. /blog
url: "" 
baseurl: /computers
 
collections:
   slide:



#Algolia seacr api key

algolia:
  application_id: 'L5J3IKHT56'
  index_name:     'getstarted_actors'
  search_only_api_key:  '050d04fdcad718ac513bdbb856415a42'

title: Cls Computers Service
description: Cls Computers servicios de reparacion de hardware y software,
             como tambien vendemos computadoras Desktops, Gaming Computers, laptops & y mucho mas.

plugins:
    - jekyll-seo-tag
    - jekyll-analytics

#Jekyll Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-121083457-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

collections:
  products:
    _hide_content: true
    output: true
  slide:
    _hide_content: true
    output: true